apiVersion: v1
kind: ConfigMap
metadata:
  name: devops2-config-mukhanovt
  labels:
    created-by: mukhanovt
data:
  app.name: "DevOps2 Application by MukhanovT"
  app.version: "1.0.0"
  spring.profiles.active: "production"