apiVersion: v1
kind: Service
metadata:
  name: devops2-service-mukhanovt
  labels:
    app: devops2-app
    created-by: mukhanovt
spec:
  type: NodePort
  selector:
    app: devops2-app
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080